name: Django Deployment Workflow

on: [push]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Change file owner
      run: |
        sudo chown -R $(id -u):$(id -g) ../../

    - name: Check if folder exists
      run: |
        echo "Linking to /var/www/${{ github.event.repository.name }}"
        sudo mkdir -p /var/www/${{ github.event.repository.name }}/static

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Build Docker Images
      run: |
        cp ../.env .
        docker-compose -f docker-compose.prod.yml build
        docker-compose -f docker-compose.prod.yml run backend python manage.py check --deploy
        docker-compose -f docker-compose.prod.yml run backend python manage.py makemigrations
        docker-compose -f docker-compose.prod.yml run backend python manage.py migrate
        docker-compose -f docker-compose.prod.yml run backend python ./manage.py createsuperuser --noinput 2> /dev/null || true

    - name: Run Deployment commands
      run: |
        docker-compose -f docker-compose.prod.yml up --build -d
